"""initial_models

Revision ID: 920f6cc7cc03
Revises: 8d39b224783b
Create Date: 2022-11-28 20:04:06.949136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from app.database import types

revision = "920f6cc7cc03"
down_revision = "8d39b224783b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuration_definition",
        sa.Column("spec", types.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "id",
            types.UUID(),
            server_default=sa.text("(GEN_RANDOM_UUID())"),
            nullable=False,
        ),
        sa.Column("labels", types.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("annotations", types.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "namespace",
        sa.Column("name", sa.Unicode(length=255), nullable=True),
        sa.Column("resource_version", sa.Integer(), nullable=True),
        sa.Column(
            "id",
            types.UUID(),
            server_default=sa.text("(GEN_RANDOM_UUID())"),
            nullable=False,
        ),
        sa.Column("labels", types.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("annotations", types.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "configuration",
        sa.Column("api_group", sa.Unicode(length=255), nullable=True),
        sa.Column("version", sa.Unicode(length=255), nullable=True),
        sa.Column("kind", sa.Unicode(length=255), nullable=True),
        sa.Column("name", sa.Unicode(length=255), nullable=True),
        sa.Column("resource_version", sa.Integer(), nullable=True),
        sa.Column("spec", types.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("status", types.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("subresources", types.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "id",
            types.UUID(),
            server_default=sa.text("(GEN_RANDOM_UUID())"),
            nullable=False,
        ),
        sa.Column("namespace", sa.Unicode(length=255), nullable=True),
        sa.ForeignKeyConstraint(["namespace"], ["namespace.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("namespace", "kind", "name", name="uq_ns_kind_name"),
    )
    op.create_table(
        "secret",
        sa.Column("resource_version", sa.Integer(), nullable=True),
        sa.Column("data", types.AESField(), nullable=True),
        sa.Column(
            "id",
            types.UUID(),
            server_default=sa.text("(GEN_RANDOM_UUID())"),
            nullable=False,
        ),
        sa.Column("namespace", sa.Unicode(length=255), nullable=True),
        sa.ForeignKeyConstraint(["namespace"], ["namespace.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("secret")
    op.drop_table("configuration")
    op.drop_table("namespace")
    op.drop_table("configuration_definition")
    # ### end Alembic commands ###
